#!/bin/bash
# /etc/init.d/myse
# debian-compatible myse startup script.
# Florent Clairambault <florent@clairambault.fr>
#
### BEGIN INIT INFO
# Provides:          myse
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start myse at boot time
# Description:       Controls myse startup
### END INIT INFO

set -x

PATH=/bin:/usr/bin:/sbin:/usr/sbin

DESC="MySE"
NAME=myse
SCRIPTNAME=/etc/init.d/$NAME

SU=/bin/su
MYSE_JAR=/usr/share/myse/myse.jar
MYSE_ARGS=-d
MYSE_USER=myse
JAVA=java
JAVA_ARGS=

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# load environments
if [ -r /etc/default/locale ]; then
  . /etc/default/locale
  export LANG LANGUAGE
elif [ -r /etc/environment ]; then
  . /etc/environment
  export LANG LANGUAGE
fi

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

# Make sure we run as root, since setting the max open files through
# ulimit requires root access
if [ `id -u` -ne 0 ]; then
    echo "The $NAME init script can only be run as root"
    exit 1
fi

#
# Function that starts the daemon/service
#
do_start()
{
    # --user in daemon doesn't prepare environment variables like HOME, USER, LOGNAME or USERNAME,
    # so we let su do so for us now
    su -l $MYSE_USER --shell=/bin/bash -c "$JAVA $JAVA_ARGS -jar $MYSE_JAR $MYSE_ARGS" || return 2
}

#
# Function that stops the daemon/service
#
do_stop()
{
    killall -u $MYSE_USER java
}

case "$1" in
  start)
    log_daemon_msg "Starting $DESC" "$NAME"
    do_start
    ;;
  stop)
    log_daemon_msg "Stopping $DESC" "$NAME"
    do_stop
    ;;
  restart|force-reload)
    do_stop
    do_start
	;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
    exit 3
    ;;
esac

exit 0
